version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /k8s
      - /test
    schedule:
      interval: daily
    groups:
      gomod:
        patterns:
          - "*"
        group-by: dependency-name
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
