- name: added-feature
  description: for new features in the changelog.
  color: a2eeef
- name: changed
  description: for changes in existing functionality in the changelog.
  color: a2eeef
- name: deprecated
  description: for soon-to-be removed features in the changelog.
  color: e4e669
- name: removed
  description: for now removed features in the changelog.
  color: e4e669
- name: bugfix
  description: for any bug fixes in the changelog.
  color: d73a4a
- name: security
  description: for vulnerabilities in the changelog.
  color: dd4739
- name: bug
  description: Something isn't working in this issue.
  color: d73a4a
- name: enhancement
  description: New feature request in this issue.
  color: a2eeef
- name: good first issue
  description: Low hanging fruit.
  color: 7057ff
- name: help wanted
  description: I need some help.
  color: 008672
