name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: go-version
    attributes:
      label: go Version
      description: What version of go are you running? `go version`
      placeholder: go version go1.18.1 linux/amd64
    validations:
      required: true

  - type: input
    id: linodego-version
    attributes:
      label: API Wrapper Version
      description: What version of our wrapper are you running?
      placeholder: github.com/linode/linodego v1.0.0
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      render: go
      label: Code Snippet
      description: If your files are too long for a short code snippet please use GitHub Gists

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: List any custom configurations and the steps to reproduce this error
    validations:
      required: true
