name: Gosec Scan
on:
  pull_request: null

jobs:
  gosec_scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run Gosec Security Scanner on root directory
        uses: securego/gosec@master
        with:
          # We need to temporarily exclude this as gosec doesn't
          # support using module files from subdirectories.
          args: -exclude-dir=k8s ./...
