name: Pull Request
on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go version

      - name: Run tidy
        run: make tidy

      - name: Run fmt
        run: go fmt ./...

      - name: Run linter
        run: make lint

      - name: Fail if changes
        run: git diff-index --exit-code HEAD
