name: Testing

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # pin@v2
        with:
          go-version: '1.18'
      - run: go version
      - name: Run tidy
        run: make tidy
      - name: Run fmt
        run: go fmt ./...
      - name: Fail if changes
        run: git diff-index --exit-code HEAD
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
        env:
          SKIP_LINT: 1
