name: Testing

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - run: go version
      - name: Run tidy
        run: make tidy
      - name: Run fmt
        run: go fmt ./...
      - name: Fail if changes
        run: git diff-index --exit-code HEAD
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
        env:
          SKIP_LINT: 1
